from pylogix import PLC

with PLC() as comm:  # No IP address needed for broadcasting
    devices = comm.Discover()
    for d in devices.Value:
        print(d.IPAddress, d.ProductName, d.Revision)


from fastapi import FastAPI
from pylogix import PLC

app = FastAPI()

@app.get("/plcs")
async def get_all_devices():
    with PLC() as comm:  # No IP address needed for broadcasting
        devices = comm.Discover()
        devices_list = []
        for d in devices.Value:
            devices_list.append(d)
    
    return devices_list

[
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "100.64.0.1",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0x377208e9",
    "ProductNameLength": 15,
    "ProductName": "ENC-HT97M13-W10",
    "State": 11
  },
  {
    "Length": 40,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.3.66",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "12.1",
    "Status": 96,
    "SerialNumber": "0x9c063da",
    "ProductNameLength": 6,
    "ProductName": "SWORD1",
    "State": 11
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.3.176",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0x377208e9",
    "ProductNameLength": 15,
    "ProductName": "ENC-HT97M13-W10",
    "State": 11
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.3.159",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "15.1",
    "Status": 96,
    "SerialNumber": "0x267d7ea8",
    "ProductNameLength": 15,
    "ProductName": "ENC-9VZ9524-W11",
    "State": 11
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.3.70",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0x167f0b65",
    "ProductNameLength": 15,
    "ProductName": "ENC-F0F31Z3-W11",
    "State": 11
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "192.168.121.1",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0x377208e9",
    "ProductNameLength": 15,
    "ProductName": "ENC-HT97M13-W10",
    "State": 11
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "192.168.159.1",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0x377208e9",
    "ProductNameLength": 15,
    "ProductName": "ENC-HT97M13-W10",
    "State": 11
  },
  {
    "Length": 56,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.63",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 200,
    "Revision": "10.7",
    "Status": 96,
    "SerialNumber": "0xd96d0c",
    "ProductNameLength": 22,
    "ProductName": "1756-EN2TR/C 217021900",
    "State": 3
  },
  {
    "Length": 45,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.70",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 166,
    "Revision": "10.7",
    "Status": 48,
    "SerialNumber": "0xce1ac7",
    "ProductNameLength": 11,
    "ProductName": "1756-EN2T/D",
    "State": 3
  },
  {
    "Length": 45,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.249",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 166,
    "Revision": "11.2",
    "Status": 48,
    "SerialNumber": "0x15fb5be",
    "ProductNameLength": 11,
    "ProductName": "1756-EN2T/D",
    "State": 3
  },
  {
    "Length": 46,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.164",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 200,
    "Revision": "11.2",
    "Status": 48,
    "SerialNumber": "0xda2839",
    "ProductNameLength": 12,
    "ProductName": "1756-EN2TR/C",
    "State": 3
  },
  {
    "Length": 62,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.165",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 108,
    "Revision": "6.12",
    "Status": 101,
    "SerialNumber": "0xd04a37c5",
    "ProductNameLength": 28,
    "ProductName": "1734-AENT/C Ethernet Adapter",
    "State": 3
  },
  {
    "Length": 63,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.78",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 196,
    "Revision": "5.12",
    "Status": 52,
    "SerialNumber": "0x6072178d",
    "ProductNameLength": 29,
    "ProductName": "1734-AENTR/B Ethernet Adapter",
    "State": 3
  },
  {
    "Length": 51,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.45",
    "VendorID": 356,
    "Vendor": "FANUC Robotics America",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 2,
    "Revision": "2.4",
    "Status": 84,
    "SerialNumber": "0xe433144a",
    "ProductNameLength": 17,
    "ProductName": "FANUC Robot R30iB",
    "State": 255
  },
  {
    "Length": 45,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.15",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 58,
    "Revision": "6.6",
    "Status": 128,
    "SerialNumber": "0x3aab0d",
    "ProductNameLength": 11,
    "ProductName": "1756-ENBT/A",
    "State": 3
  },
  {
    "Length": 46,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.166",
    "VendorID": 7,
    "Vendor": "SMC Corporation",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 203,
    "Revision": "1.1",
    "Status": 97,
    "SerialNumber": "0x520103bb",
    "ProductNameLength": 12,
    "ProductName": "EX600-SEN3/4",
    "State": 255
  },
  {
    "Length": 45,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.74",
    "VendorID": 1,
    "Vendor": "Rockwell Automation/Allen-Bradley",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 90,
    "Revision": "4.2",
    "Status": 96,
    "SerialNumber": "0x405462d9",
    "ProductNameLength": 11,
    "ProductName": "1794-AENT/B",
    "State": 3
  },
  {
    "Length": 48,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.58",
    "VendorID": 283,
    "Vendor": "Hilscher GmbH",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 275,
    "Revision": "1.1",
    "Status": 0,
    "SerialNumber": "0x51d2",
    "ProductNameLength": 14,
    "ProductName": "Generic Device",
    "State": 3
  },
  {
    "Length": 48,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.48",
    "VendorID": 283,
    "Vendor": "Hilscher GmbH",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 275,
    "Revision": "1.1",
    "Status": 96,
    "SerialNumber": "0x50cb",
    "ProductNameLength": 14,
    "ProductName": "Generic Device",
    "State": 3
  },
  {
    "Length": 48,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.57",
    "VendorID": 283,
    "Vendor": "Hilscher GmbH",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 275,
    "Revision": "1.1",
    "Status": 0,
    "SerialNumber": "0x56c1",
    "ProductNameLength": 14,
    "ProductName": "Generic Device",
    "State": 3
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.153",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0x377208e9",
    "ProductNameLength": 15,
    "ProductName": "ENC-HT97M13-W10",
    "State": 11
  },
  {
    "Length": 49,
    "EncapsulationVersion": 1,
    "IPAddress": "172.22.5.151",
    "VendorID": 77,
    "Vendor": "Rockwell Software, Inc.",
    "DeviceID": 12,
    "DeviceType": "Communications Adapter",
    "ProductCode": 115,
    "Revision": "13.1",
    "Status": 96,
    "SerialNumber": "0xd0d4b8a",
    "ProductNameLength": 15,
    "ProductName": "ENC-3Z1T2K2-W10",
    "State": 11
  }
]
