// seeders/populate_cost_codes.js
const Projects = require("../models/project"); // Import the model
const { sequelize } = require("../config/db"); // Import the Sequelize instance

// Sample data for cost codes
const projectsData = [
  {
    number: "Nothing",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Nothing",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 1,
  },
  {
    number: "Admin",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Admin",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 1,
  },
  {
    number: "Vacation",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Vac",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 1,
  },
  {
    number: "Absence",
    description: "Absence - Time Off",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Abs",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Holiday",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Hol",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Proposal",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Prop",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "PDEV",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "PDEV",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Sales",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Sales",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Sick",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Sick",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Jury Duty",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Jury",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Bereavement",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Berev",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "ProjOver",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "ProjOv",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Training",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Train",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "SpareParts",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "SParts",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "COVID19",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "CV19",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "Unnassigned",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "UnnaSign",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "PDUP",
    description: "",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "Pdup",
    comment: "",
    overtime: 0,
    sga_flag: 0,
    customer_id: 1,
  },
  {
    number: "24-3019",
    description: "Honda Paint and Sanding Powder",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "HndPS",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 2,
  },
  {
    number: "24-3012",
    description: "Tesla Cybertruck",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "TslaCyTck",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 1002,
  },
  {
    number: "24-3013",
    description: "Stellantis Butterfly Valves",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "StllBV",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 1003,
  },
  {
    number: "24-3014",
    description: "Liberty City Remake",
    start_date: new Date(),
    end_date: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    short_name: "LibCyRmk",
    comment: "",
    overtime: 1,
    sga_flag: 1,
    customer_id: 1004,
  },
];

// Function to populate the cost_codes table
const populateProjects = async () => {
  try {
    await sequelize.sync(); // Ensure the database and table are created
    await Projects.bulkCreate(projectsData); // Insert the seed data into the table
    console.log("Cost codes have been successfully populated.");
  } catch (error) {
    console.error("Error populating cost codes:", error);
  } finally {
    await sequelize.close(); // Close the connection to avoid hanging scripts
  }
};

populateProjects();
